# Generated by Django 4.1.1 on 2022-09-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_order_updated_at_order_email_order_ordered_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="items", to="store.item"
            ),
        ),
    ]
