# Generated by Django 4.1.1 on 2022-09-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.TextField(null=True),
        ),
    ]
