version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: AppDockerfile
    container_name: django-project
    volumes:
      - .:/django-project
      - static:/usr/src/app/static
    ports:
      - 8080:8000

volumes:
  db_data:
  static:
